### ISSUE TITLE
 yuque-dl server ./download/翼康养老 失敗

### ISSUE THREAD

**Issue by Elex92** [gxr404/yuque-dl#28]
![image](https://github.com/gxr404/yuque-dl/assets/16713043/68619b4e-22d4-40b5-b82f-5f1280800835)
 C:\Users\15424\Desktop> yuque-dl server ./download/翼康养老APP-线上
✘ [ERROR] Legacy octal escape sequences cannot be used in an ECMAScript module

    download/翼康养老APP-线上/.vitepress/config.ts:3:20:
      3 │     title: "C:\Users\15424\Desktop\download\翼康养老APP-线上",
        ╵                     ~~~~

  This file is considered to be an ECMAScript module because of the "export" keyword here:

    download/翼康养老APP-线上/.vitepress/config.ts:2:2:
      2 │   export default {
        ╵   ~~~~~~

failed to load config from C:\Users\15424\Desktop\download\翼康养老APP-线上\.vitepress\config.ts
Error: Build failed with 1 error:
download/翼康养老APP-线上/.vitepress/config.ts:3:20: ERROR: Legacy octal escape sequences cannot be used in an ECMAScript module
    at failureErrorWithLog (C:\Users\15424\AppData\Roaming\nvm\v16.15.0\node_modules\yuque-dl\node_modules\esbuild\lib\main.js:1472:15)
    at C:\Users\15424\AppData\Roaming\nvm\v16.15.0\node_modules\yuque-dl\node_modules\esbuild\lib\main.js:945:25
    at runOnEndCallbacks (C:\Users\15424\AppData\Roaming\nvm\v16.15.0\node_modules\yuque-dl\node_modules\esbuild\lib\main.js:1315:45)
    at buildResponseToResult (C:\Users\15424\AppData\Roaming\nvm\v16.15.0\node_modules\yuque-dl\node_modules\esbuild\lib\main.js:943:7)
    at C:\Users\15424\AppData\Roaming\nvm\v16.15.0\node_modules\yuque-dl\node_modules\esbuild\lib\main.js:970:16
    at responseCallbacks.<computed> (C:\Users\15424\AppData\Roaming\nvm\v16.15.0\node_modules\yuque-dl\node_modules\esbuild\lib\main.js:622:9)
    at handleIncomingPacket (C:\Users\15424\AppData\Roaming\nvm\v16.15.0\node_modules\yuque-dl\node_modules\esbuild\lib\main.js:677:12)
    at Socket.readFromStdout (C:\Users\15424\AppData\Roaming\nvm\v16.15.0\node_modules\yuque-dl\node_modules\esbuild\lib\main.js:600:7)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
}

**Comment by gxr404** [comment]
已修复, 请更新至`1.0.57`

**Comment by Elex92** [comment]
好的
