### ISSUE TITLE
 [vitepress] Internal server error: Element is missing end tag.

### ISSUE THREAD

**Issue by Elex92** [gxr404/yuque-dl#29]
https://www.yuque.com/i-meng/izcrzz/nh5fwrgzd6e15iip下载保存本地，启动本地服务部分页面报错
15:30:07 [vitepress] Internal server error: Element is missing end tag.
  Plugin: vite:vue
  File: C:/Users/15424/Desktop/download/download/翼康养老APP-线上/设备绑定.md:239:51
  243|  ### 新建鉴权模块单例
  244|  > 1. 检查蓝牙授权方法
  245|  > 2. 请求用户授权方法
     |             ^
  246|  > 3. 检查蓝牙功能
  247|
      at createCompilerError (C:\Users\15424\AppData\Roaming\npm\node_modules\yuque-dl\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:1328:17)
      at emitError (C:\Users\15424\AppData\Roaming\npm\node_modules\yuque-dl\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:2812:5)
      at Object.onclosetag (C:\Users\15424\AppData\Roaming\npm\node_modules\yuque-dl\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:2179:13)
      at Tokenizer.stateInClosingTagName (C:\Users\15424\AppData\Roaming\npm\node_modules\yuque-dl\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:749:16)
      at Tokenizer.parse (C:\Users\15424\AppData\Roaming\npm\node_modules\yuque-dl\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:1107:16)
      at Object.baseParse (C:\Users\15424\AppData\Roaming\npm\node_modules\yuque-dl\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:2851:13)
      at Object.parse (C:\Users\15424\AppData\Roaming\npm\node_modules\yuque-dl\node_modules\@vue\compiler-dom\dist\compiler-dom.cjs.js:706:23)
      at Object.parse$2 [as parse] (C:\Users\15424\AppData\Roaming\npm\node_modules\yuque-dl\node_modules\@vue\compiler-sfc\dist\compiler-sfc.cjs.js:1850:24)
      at createDescriptor (file:///C:/Users/15424/AppData/Roaming/npm/node_modules/yuque-dl/node_modules/@vitejs/plugin-vue/dist/index.mjs:64:43)
      at transformMain (file:///C:/Users/15424/AppData/Roaming/npm/node_modules/yuque-dl/node_modules/@vitejs/plugin-vue/dist/index.mjs:2376:34)

**Comment by gxr404** [comment]
已修复,更新至`1.0.58`
server功能没什么人用 bug有点多😂

**Comment by Elex92** [comment]
好的 感谢
