### ISSUE TITLE
私有知识库带 token 也没法下载

### ISSUE THREAD

**Issue by dzfs** [gxr404/yuque-dl#45]
这个报错应该不是token错误吧？我反复确定过没问题，暂时不清楚是什么情况。

```
(node:58632) UnhandledPromiseRejectionWarning: Error: Not supported
    at run (/Users/user/.nvm/versions/node/v10.20.1/lib/node_modules/yuque-dl/bin/index.js:4:3)
    at Object.<anonymous> (/Users/user/.nvm/versions/node/v10.20.1/lib/node_modules/yuque-dl/bin/index.js:6:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
(node:58632) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:58632) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by gxr404** [comment]
nodejs 版本太低了`v10.20.1 `, [请使用`18.4`以上的](https://github.com/gxr404/yuque-dl#prerequisite)

**Comment by dzfs** [comment]
> nodejs 版本太低了`v10.20.1 `, [请使用`18.4`以上的](https://github.com/gxr404/yuque-dl#prerequisite)

谢谢！抱歉没注意到
